// angular/src/app/components/task-modal/task-modal.component.ts
import { Component, EventEmitter, Input, Output } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { Task } from '../../models/task';

@Component({
  selector: 'tf-task-modal',
  standalone: true,
  imports: [CommonModule, FormsModule],
  template: `
    <div class="modal-backdrop" role="dialog" aria-modal="true" *ngIf="open">
      <div class="modal">
        <header class="modal-header">
          <h2 class="modal-title">
            {{ mode === 'create' ? 'Criar tarefa' : 'Editar tarefa' }}
          </h2>
        </header>

        <form class="modal-body" (ngSubmit)="onSubmitInternal()" novalidate>
          <div class="form-field">
            <label class="form-label" for="task-title">Título</label>
            <input
              id="task-title"
              class="form-input"
              [(ngModel)]="title"
              name="title"
              placeholder="Ex.: Revisar questionário SUS"
            />
          </div>

          <div class="form-field">
            <label class="form-label" for="task-description">Descrição</label>
            <textarea
              id="task-description"
              class="form-input form-textarea"
              [(ngModel)]="description"
              name="description"
              placeholder="Detalhes adicionais da atividade..."
            ></textarea>
          </div>

          <p *ngIf="hasError()" class="form-error">
            Título e descrição são obrigatórios.
          </p>

          <footer class="modal-footer">
            <button type="button" class="app-button app-button-ghost" (click)="onClose.emit()">
              Cancelar
            </button>
            <button type="submit" class="app-button">
              {{ mode === 'create' ? 'Criar' : 'Salvar' }}
            </button>
          </footer>
        </form>
      </div>
    </div>
  `,
})
export class TaskModalComponent {
  @Input() open = false;
  @Input() mode: 'create' | 'edit' = 'create';
  @Input() initialTask: Task | null = null;

  @Output() submitTask = new EventEmitter<{ title: string; description: string }>();
  @Output() onClose = new EventEmitter<void>();

  title = '';
  description = '';
  touched = false;

  ngOnChanges(): void {
    if (this.open && this.initialTask && this.mode === 'edit') {
      this.title = this.initialTask.title;
      this.description = this.initialTask.description;
      this.touched = false;
    }
    if (this.open && this.mode === 'create') {
      this.title = '';
      this.description = '';
      this.touched = false;
    }
  }

  hasError(): boolean {
    return this.touched && (!this.title.trim() || !this.description.trim());
  }

  onSubmitInternal(): void {
    this.touched = true;
    if (!this.title.trim() || !this.description.trim()) {
      return;
    }
    this.submitTask.emit({
      title: this.title.trim(),
      description: this.description.trim(),
    });
  }
}

// react/src/components/TaskModal.tsx
import type { FormEvent } from 'react';
import { useEffect, useState } from 'react';
import type { Task } from '../context/TaskContext';

interface TaskModalProps {
  open: boolean;
  mode: 'create' | 'edit';
  initialTask?: Task;
  onClose: () => void;
  onSubmit: (data: { title: string; description: string }) => void;
}

export const TaskModal = ({ open, mode, initialTask, onClose, onSubmit }: TaskModalProps) => {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [touched, setTouched] = useState(false);

  useEffect(() => {
    if (open && initialTask && mode === 'edit') {
      setTitle(initialTask.title);
      setDescription(initialTask.description);
      setTouched(false);
    }
    if (open && mode === 'create') {
      setTitle('');
      setDescription('');
      setTouched(false);
    }
  }, [open, initialTask, mode]);

  if (!open) return null;

  const handleSubmit = (event: FormEvent) => {
    event.preventDefault();
    setTouched(true);
    if (!title.trim() || !description.trim()) return;
    onSubmit({ title: title.trim(), description: description.trim() });
  };

  const hasError = touched && (!title.trim() || !description.trim());

  return (
    <div className="modal-backdrop" role="dialog" aria-modal="true">
      <div className="modal">
        <header className="modal-header">
          <h2 className="modal-title">
            {mode === 'create' ? 'Criar tarefa' : 'Editar tarefa'}
          </h2>
        </header>
        <form className="modal-body" onSubmit={handleSubmit}>
          <div className="form-field">
            <label htmlFor="task-title" className="form-label">
              Título
            </label>
            <input
              id="task-title"
              className="form-input"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="Ex.: Revisar questionário SUS"
            />
          </div>
          <div className="form-field">
            <label htmlFor="task-description" className="form-label">
              Descrição
            </label>
            <textarea
              id="task-description"
              className="form-input form-textarea"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Detalhes adicionais da atividade..."
            />
          </div>
          {hasError && (
            <p className="form-error">Título e descrição são obrigatórios.</p>
          )}
          <footer className="modal-footer">
            <button
              type="button"
              className="app-button app-button-ghost"
              onClick={onClose}
            >
              Cancelar
            </button>
            <button type="submit" className="app-button">
              {mode === 'create' ? 'Criar' : 'Salvar'}
            </button>
          </footer>
        </form>
      </div>
    </div>
  );
};
